name: ngpidgin
description: Nigerian Pidgin Dictionary.
version: 1.0.0+1

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2 #todo: review
  flutter_riverpod: ^2.1.3
  cupertino_icons: ^1.0.5 #todo: remove
  flutter_svg: ^0.23.0+1
  flutter_tts: ^4.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.15
  sqflite: ^2.4.1 #todo: remove
  path: ^1.8.2
  # flutter_html: ^2.2.1
  http: ^1.2.2
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.3.5
  cloud_firestore: ^5.4.5
  flutter_widget_from_html_core: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/icons/
    - assets/language_packs/
    - assets/datastore/dictionary_store.db

  fonts:
    - family: Poppins
      fonts:
        # - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        #   weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        # - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        #   weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
